### ISSUE TITLE
dependency error

### ISSUE THREAD

**Issue by On-JungWoan** [jyunlee/InterHandGen#3]
What is the version of Python you used? I got a dependency error for Python 3.10, 3.9. 3.8.

![image](https://github.com/jyunlee/InterHandGen/assets/84084372/7bd51d22-875f-45ae-a13e-052d98cd4c52)

**Comment by jyunlee** [comment]
Hello, thanks for your interest in our work! I'm using Python 3.9.18, but that error is caused by specifying two versions of Pillow library during installation. Can you remove Pillow==10.2.0 line and try again?

Let me know if this solves the issue.

**Comment by On-JungWoan** [comment]
Hello @jyunlee, thank you for your response, and I'm sorry for the late response. I've solved the problem by making a simple shell file. I will share the shell file.

- **shell file**

```shell
#############
## pytorch ##
#############
conda install pytorch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 pytorch-cuda=11.7 -c pytorch -c nvidia


###############
## pytorch3d ##
###############
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
# conda install -c bottler nvidiacub # For users who used an older version of the CUDA than 11.7
curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
tar xzf 1.10.0.tar.gz && rm 1.10.0.tar.gz
export CUB_HOME=$PWD/cub-1.10.0
conda install pytorch3d -c pytorch3d


##########
## etc. ##
##########
pip install -r requirements.txt
```

- **requirements.txt**

```
higher>=0.2.1
jax>=0.4.25
matplotlib>=3.6.3
mxnet-mkl==1.6.0
numpy==1.23.1
opacus>=1.4.1
opencv_contrib_python>=4.7.0.72
opencv_python>=4.5.5.64
pandas>=1.5.3
Pillow>=9.2.0
Pillow>=10.2.0
PyYAML>=6.0
PyYAML>=6.0.1
scikit_learn>=1.2.1
scipy>=1.5.2
setuptools>=59.6.0
setuptools>=59.5.0
six>=1.16.0
tqdm>=4.64.1
trimesh>=3.18.3
tvm>=1.0.0
plotly
chumpy
```

**Comment by On-JungWoan** [comment]
And, there is a misspelling in the README.md(Environment Setup - 2). The installation command should be changed to:

```
 $ cd utils
 $ git clone https://github.com/ThibaultGROUEIX/ChamferDistancePytorch.git
 $ cd ChamferDistancePytorch/chamfer3D  #(mv to cd)
 $ python setup.py install 
```
